; Global defaults applied to all models below
[*]
host = 0.0.0.0
port = 8080
models-max = 1
models-autoload = 1
flash-attn = on
threads = 16
jinja = true
np = 1
load-mode = dio
cache-type-k = q4_0
cache-type-v = q4_0
ubatch-size = 2048
kv-unified = true
dry-multiplier = 0.8
dry-base = 1.75
repeat-penalty = 1.0
frequency-penalty = 0.2

;[Ternary-Bonsai-27B:Q2_0]
;llama-root = /home/bazzite/Develop/llama-cpp_prismml/build_hip/bin
;model = /home/bazzite/Work/HF/Ternary-Bonsai-27B-Q2_0.gguf
;ctx-size = 128000
;ngl = 999
;temp = 0.9
;top-p = 0.95
;spec-draft-model = /home/bazzite/Work/HF/Ternary-Bonsai-27B-dspark-Q4_1.gguf
;spec-type = draft-simple
;spec-draft-n-max = 4


[M-Gemma4-26B-A3B_QAT:Q4_K_XL]
model = /home/bazzite/Work/HF/gemma-4-26B-A4B-it-qat-UD-Q4_K_XL.gguf
model-draft = /home/bazzite/Work/HF/mtp-gemma-4-26B-A4B-it-F16.gguf
dev = ROCm0
ctx-size = 128000
temp = 0.9
top-p = 0.95
min-p = 0.01
ncmoe = 28
spec-type = draft-mtp
spec-draft-n-max = 2
cache-type-k-draft = q4_0
cache-type-v-draft = q4_0

[M-Gemma4-E4B_QAT:Q4_K_XL]
model = /home/bazzite/Work/HF/gemma-4-E4B-it-qat-UD-Q4_K_XL.gguf
model-draft = /home/bazzite/Work/HF/mtp-gemma-4-E4B-it-F16.gguf
dev = ROCm0
n-gpu-layers = 99
ctx-size = 128000
temp = 0.9
top-p = 0.95
min-p = 0.01
spec-type = draft-mtp
spec-draft-n-max = 2
cache-type-k-draft = q4_0
cache-type-v-draft = q4_0

[M-GLM-4.7-Flash-REAP-23B-A3B:Q4_K_XL]
model = /home/bazzite/Work/HF/GLM-4.7-Flash-REAP-23B-A3B-UD-Q4_K_XL.gguf
dev = ROCm0
ctx-size = 192000
temp = 0.9
top-p = 0.95
min-p = 0.01
cmoe = true
reasoning-preserve = true

[M-Grug-35b:Q4_K_M]
model = /home/bazzite/Work/HF/grug-35b-qat-Q4_K_M.gguf
dev = ROCm0
ctx-size = 192000
temp = 0.9
top-p = 0.95
min-p = 0.01
ncmoe = 36
reasoning-preserve = true

[M-Kwaipilot_KAT-Coder-V2.5:IQ4_NL]
model = /home/bazzite/Work/HF/Kwaipilot_KAT-Coder-V2.5-Dev-IQ4_NL.gguf
dev = ROCm0
ctx-size = 128000
temp = 0.9
top-p = 0.95
min-p = 0.01
cmoe = true
reasoning-preserve = true

[M-Laguna-XS-2.1:Q4_K_M]
model = /home/bazzite/Work/HF/Laguna-XS-2.1-Q4_K_M.gguf
dev = ROCm0
ctx-size = 128000
temp = 0.9
top-p = 0.95
min-p = 0.01
cmoe = true
reasoning-preserve = true

[L-Laguna-S-2.1:UD-IQ3_XXS]
model = /home/bazzite/Work/HF/Laguna-S-2.1-UD-IQ3_XXS.gguf
dev = ROCm0
ctx-size = 128000
temp = 0.9
top-p = 0.95
min-p = 0.01
cmoe = true
reasoning-preserve = true

[M-LFM2.5-8B-A1B:Q4_K_XL]
model = /home/bazzite/Work/HF/LFM2.5-8B-A1B-UD-Q4_K_XL.gguf
dev = ROCm0
ctx-size = 96000
temp = 0.9
top-p = 0.95
min-p = 0.01

;[Muse-Glimmer-30B:UD-IQ2_M]
;model = /home/bazzite/Work/HF/Muse-Glimmer-30B-UD-IQ2_M.gguf
;dev = ROCm0
;ctx-size = 96000
;temp = 0.9
;top-p = 0.95
;min-p = 0.01

[L-Mistral-Small-4-119B:UD-IQ3_S]
model = /home/bazzite/Work/HF/Mistral-Small-4-119B-2603-UD-IQ3_S.gguf
dev = ROCm0
ctx-size = 192000
temp = 0.9
top-p = 0.95
min-p = 0.01
cmoe = true
reasoning-preserve = true

[M-Nemotron-3-Nano-Omni-30B-A3B:IQ3_S]
model = /home/bazzite/Work/HF/NVIDIA-Nemotron-3-Nano-Omni-30B-A3B-Reasoning-UD-IQ3_S.gguf
dev = ROCm0
ctx-size = 192000
temp = 0.9
top-p = 0.95
min-p = 0.01
ncmoe = 44
reasoning-preserve = true

[M-Nemotron-3.5-Lightning-30B-A3B:IQ4_NL]
model = /home/bazzite/Work/HF/NVIDIA-Nemotron-3.5-Lightning-30B-A3B-IQ4_NL.gguf
dev = ROCm0
ctx-size = 192000
temp = 0.9
top-p = 0.95
min-p = 0.01
ncmoe = 44
reasoning-preserve = true

[M-Nemotron-Cascade-2-30B-A3B:IQ4_NL]
model = /home/bazzite/Work/HF/nvidia_Nemotron-Cascade-2-30B-A3B-IQ4_NL.gguf
dev = ROCm0
ctx-size = 192000
temp = 0.9
top-p = 0.95
min-p = 0.01
ncmoe = 44
reasoning-preserve = true

[M-Ornith-9B-MTP:Q4_K_M]
model = /home/bazzite/Work/HF/Ornith-1.0-9B-MTP-Q4_K_M.gguf
dev = ROCm0
ctx-size = 64000
temp = 0.9
top-p = 0.95
min-p = 0.01
reasoning-preserve = true

[M-Ornith-35B:Q4_K_M]
model = /home/bazzite/Work/HF/ornith-1.0-35b-Q4_K_M.gguf
dev = ROCm0
ctx-size = 192000
temp = 0.9
top-p = 0.95
min-p = 0.01
ncmoe = 36
reasoning-preserve = true

[M-Qwen3.5-9B:Q4_K_M]
model = /home/bazzite/Work/HF/Qwen3.5-9B-Q4_K_M.gguf
dev = ROCm0
ctx-size = 128000
temp = 0.9
top-p = 0.95
min-p = 0.01
reasoning-preserve = true

[L-Qwen3.5-122B-A10B:UD-IQ3_S]
model = /home/bazzite/Work/HF/Qwen3.5-122B-A10B-UD-IQ3_S.gguf
dev = ROCm0
ctx-size = 128000
temp = 0.9
top-p = 0.95
min-p = 0.01
ncmoe = 48
reasoning-preserve = true

[L-Qwen3-Coder-Next:UD-IQ4_NL]
model = /home/bazzite/Work/HF/Qwen3-Coder-Next-UD-IQ4_NL.gguf
dev = ROCm0
ctx-size = 128000
temp = 0.9
top-p = 0.95
min-p = 0.01
cmoe = true
reasoning-preserve = true

[M-Qwen3.6-35B-A3B:IQ4_NL]
model = /home/bazzite/Work/HF/Qwen3.6-35B-A3B-UD-IQ4_NL.gguf
dev = ROCm0
ctx-size = 192000
temp = 0.9
top-p = 0.95
min-p = 0.01
ncmoe = 36
reasoning-preserve = true

[M-Qwopus3.6-35B-A3B:Q4_K_M]
model = /home/bazzite/Work/HF/Qwopus3.6-35B-A3B-Coder-MTP-Q4_K_M.gguf
dev = ROCm0
ctx-size = 192000
temp = 0.9
top-p = 0.95
min-p = 0.01
ncmoe = 36
reasoning-preserve = true
