version = 1

; Global defaults applied to all models below
[*]
models-max = 1
models-autoload = 1
flash-attn = on
threads = 16
jinja = true
dev = ROCm0
np = 1
load-mode = mlock
cache-type-k = q4_0
cache-type-v = q4_0
ubatch-size = 2048
kv-unified = true

[Gemma4-26B-A3B_QAT:Q4_K_XL]
model = /home/bazzite/Work/HF/gemma-4-26B-A4B-it-qat-UD-Q4_K_XL.gguf
model-draft = /home/bazzite/Work/HF/mtp-gemma-4-26B-A4B-it-F16.gguf
ctx-size = 96000
temp = 0.9
top-p = 0.95
min-p = 0.01
ncmoe = 28
spec-type = draft-mtp
spec-draft-n-max = 2
cache-type-k-draft = q4_0
cache-type-v-draft = q4_0

[Gemma4-E4B_QAT:Q4_K_XL]
model = /home/bazzite/Work/HF/gemma-4-E4B-it-qat-UD-Q4_K_XL.gguf
model-draft = /home/bazzite/Work/HF/mtp-gemma-4-E4B-it-F16.gguf
n-gpu-layers = 99
ctx-size = 96000
temp = 0.9
top-p = 0.95
min-p = 0.01
spec-type = draft-mtp
spec-draft-n-max = 2
cache-type-k-draft = q4_0
cache-type-v-draft = q4_0

[GLM-4.7-Flash-REAP-23B-A3B:Q4_K_XL]
model = /home/bazzite/Work/HF/GLM-4.7-Flash-REAP-23B-A3B-UD-Q4_K_XL.gguf
ctx-size = 192000
temp = 0.9
top-p = 0.95
min-p = 0.01
cmoe = true
reasoning-preserve = true

[Laguna-S-2.1:UD-IQ3_XXS]
model = /home/bazzite/Work/HF/Laguna-S-2.1-UD-IQ3_XXS.gguf
ctx-size = 128000
temp = 0.9
top-p = 0.95
min-p = 0.01
cmoe = true
reasoning-preserve = true

[LFM2.5-8B-A1B:Q4_K_XL]
model = /home/bazzite/Work/HF/LFM2.5-8B-A1B-UD-Q4_K_XL.gguf
ctx-size = 96000
temp = 0.9
top-p = 0.95
min-p = 0.01

[NVIDIA-Nemotron-3-Nano-Omni-30B-A3B:IQ3_S]
model = /home/bazzite/Work/HF/NVIDIA-Nemotron-3-Nano-Omni-30B-A3B-Reasoning-UD-IQ3_S.gguf
ctx-size = 192000
temp = 0.9
top-p = 0.95
min-p = 0.01
ncmoe = 44
reasoning-preserve = true

[OpenNemo-Cascade-2-30B-A3B:IQ4_XS]
model = /home/bazzite/Work/HF/openNemo-Cascade-2-30B-A3B.IQ4_XS.gguf
ctx-size = 192000
temp = 0.9
top-p = 0.95
min-p = 0.01
ncmoe = 44
reasoning-preserve = true

[Ornith-9B-MTP:Q4_K_M]
model = /home/bazzite/Work/HF/Ornith-1.0-9B-MTP-Q4_K_M.gguf
ctx-size = 64000
temp = 0.9
top-p = 0.95
min-p = 0.01
reasoning-preserve = true

[Ornith-35B:Q4_K_M]
model = /home/bazzite/Work/HF/ornith-1.0-35b-Q4_K_M.gguf
ctx-size = 192000
temp = 0.9
top-p = 0.95
min-p = 0.01
ncmoe = 36
reasoning-preserve = true


[Qwopus3.6-35B-A3B:Q3_K_M]
model = /home/bazzite/Work/HF/Qwopus3.6-35B-A3B-Coder-MTP-Q3_K_M.gguf
ctx-size = 192000
temp = 0.9
top-p = 0.95
min-p = 0.01
ncmoe = 36
spec-type = draft-mtp
spec-draft-n-max = 2
cache-type-k-draft = q4_0
cache-type-v-draft = q4_0
reasoning-preserve = true
