version = 1

; Global defaults applied to all models below
[*]
models-max = 1
models-autoload = 1
flash-attn = on
threads = 16
jinja = true
dev = ROCm0
np = 1
no-mmap = true
cache-type-k = q5_0
cache-type-v = iq4_nl

[Qwen3.6-35B-A3B:Q3_K_M]
model = /home/bazzite/Work/HF/Qwen3.6-35B-A3B-UD-Q3_K_M.gguf
ctx-size = 192000
temp = 0.9
top-p = 0.95
top-k = 20
min-p = 0.01
ncmoe = 36
spec-type = draft-mtp
spec-draft-n-max = 2
cache-type-k-draft = q5_0
cache-type-v-draft = iq4_nl

[Qwopus3.6-35B-A3B:Q3_K_M]
model = /home/bazzite/Work/HF/Qwopus3.6-35B-A3B-Coder-MTP-Q3_K_M.gguf
ctx-size = 192000
temp = 0.9
top-p = 0.95
top-k = 20
min-p = 0.01
ncmoe = 36
spec-type = draft-mtp
spec-draft-n-max = 2
cache-type-k-draft = q5_0
cache-type-v-draft = iq4_nl

[Nex-N2-mini:Q3_K_XL]
model = /home/bazzite/Work/HF/Nex-N2-mini-UD-Q3_K_XL.gguf
ctx-size = 192000
temp = 0.9
top-p = 0.95
top-k = 20
min-p = 0.01
ncmoe = 35

[North-Mini-Code:IQ3]
model = /home/bazzite/Work/HF/North-Mini-Code-1.0-UD-IQ3_S.gguf
ctx-size = 192000
temp = 0.9
top-p = 0.95
top-k = 20
min-p = 0.01

[Gemmopus-26B-A3B_QAT:Q4_K_M]
model = /home/bazzite/Work/HF/Gemopus-4-26B-A4B-it-Preview-Q4_K_M.gguf
ctx-size = 96000
temp = 0.9
top-p = 0.95
top-k = 64
min-p = 0.01
ncmoe = 22

[Gemma4-26B-A3B_QAT:Q4_K_XL]
model = /home/bazzite/Work/HF/gemma-4-26B_q4_0-it.gguf
ctx-size = 96000
temp = 0.9
top-p = 0.95
top-k = 64
min-p = 0.01
ncmoe = 22

[Gemma4-21B-A4B_REAP:Q4_K_L]
model = /home/bazzite/Work/HF/gemma-4-21b-a4b-it-REAP-heretic.Q3_K_L.gguf
ctx-size = 96000
temp = 0.9
top-p = 0.95
top-k = 64
min-p = 0.01
ncmoe = 20

[Gemma4-12B_QAT:Q4_0]
model = /home/bazzite/Work/HF//home/bazzite/Work/HF/gemma-4-12b-it-qat-q4_0.gguf
n-gpu-layers = 99
ctx-size = 96000
temp = 0.9
top-p = 0.95
top-k = 64
min-p = 0.01

[Gemma4-Coding:Q4_K_M]
model = /home/bazzite/Work/HF//home/bazzite/Work/HF/gemma4-coding-Q4_K_M.gguf
n-gpu-layers = 99
ctx-size = 96000
temp = 0.9
top-p = 0.95
top-k = 64
min-p = 0.01

[Gemma4-E4B_QAT:Q4_K_XL]
model = /home/bazzite/Work/HF/gemma-4-E4B-it-qat-UD-Q4_K_XL.gguf
n-gpu-layers = 99
ctx-size = 96000
temp = 0.9
top-p = 0.95
top-k = 64
min-p = 0.01

[GLM-4.7-Flash-REAP-23B-A3B:Q4_K_XL]
model = /home/bazzite/Work/HF/GLM-4.7-Flash-REAP-23B-A3B-UD-Q4_K_XL.gguf
ctx-size = 192000
temp = 0.9
top-p = 0.95
top-k = 20
min-p = 0.01
cmoe = true

[LFM2.5-8B-A1B:Q4_K_XL]
model = /home/bazzite/Work/HF/LFM2.5-8B-A1B-UD-Q4_K_XL.gguf
ctx-size = 96000
temp = 0.9
top-p = 0.95
top-k = 64
min-p = 0.01

[Mellum2-12B-A2.5B:Q4_K_M]
model = /home/bazzite/Work/HF/Mellum2-12B-A2.5B-Thinking-Q4_K_M.gguf
ctx-size = 96000
temp = 0.9
top-p = 0.95
top-k = 64
min-p = 0.01
ncmoe = 12

[NVIDIA-Nemotron-3-Nano-Omni-30B-A3B:IQ3_S]
model = /home/bazzite/Work/HF/NVIDIA-Nemotron-3-Nano-Omni-30B-A3B-Reasoning-UD-IQ3_S.gguf
ctx-size = 192000
temp = 0.9
top-p = 0.95
top-k = 64
min-p = 0.01
ncmoe = 44

[Ornith-9B:Q5_K_M]
model = /home/bazzite/Work/HF/ornith-1.0-9b-Q5_K_M.gguf
ctx-size = 96000
temp = 0.9
top-p = 0.95
top-k = 64
min-p = 0.01

[Ornith-35B:Q4_K_M]
model = /home/bazzite/Work/HF/ornith-1.0-35b-Q4_K_M.gguf
ctx-size = 192000
temp = 0.9
top-p = 0.95
top-k = 64
min-p = 0.01
ncmoe = 36

[VibeThinker-3B:Q4_K_M]
model = /home/bazzite/Work/HF/vibethinker-3b-q4_k_m.gguf
ctx-size = 96000
temp = 0.9
top-p = 0.95
top-k = 64
min-p = 0.01
