; Global defaults applied to all models below
[*]
host = 0.0.0.0
port = 8080
models-max = 3
models-autoload = 1
flash-attn = on
threads = 16
jinja = true
np = 3
load-mode = dio
cache-type-k = q8_0
cache-type-v = q4_0
ubatch-size = 2048
kv-unified = true
dry-multiplier = 0.8
dry-base = 1.75
repeat-penalty = 1.0
frequency-penalty = 0.2

[S-Gemma4-E4B_QAT:Q4_K_XL]
model = /home/bazzite/Work/HF/gemma-4-E4B-it-qat-UD-Q4_K_XL.gguf
model-draft = /home/bazzite/Work/HF/mtp-gemma-4-E4B-it-F16.gguf
dev = none
ctx-size = 96000
reasoning-preserve = true
spec-type = draft-mtp
spec-draft-n-max = 2
cache-type-k-draft = q8_0
cache-type-v-draft = q4_0

[S-Grug-3B:Q4_K_M]
model = /home/bazzite/Work/HF/grug-3b-qat-q4-Q4_K_M.gguf
dev = none
ctx-size = 96000
ncmoe = 36
reasoning-preserve = true

[S-LFM2.5-8B-A1B:Q4_K_XL]
model = /home/bazzite/Work/HF/LFM2.5-8B-A1B-UD-Q4_K_XL.gguf
dev = none
ctx-size = 96000
reasoning-preserve = true

[S-Ling-3.0-tiny:Q5_K_M]
model = /home/bazzite/Work/HF/Ling-3.0-tiny-Q5_K_M.gguf
dev = none
ctx-size = 96000
ncmoe = 12
reasoning-preserve = true

;[S-Qwen3.5-4B:IQ4_NL]
;model = /home/bazzite/Work/HF/Qwen3.5-4B-IQ4_NL.gguf
[S-Qwen3.8-4B:Q6_K]
model = /home/bazzite/Work/HF/Qwen3.8-4B-Q6_K.gguf
dev = none
ctx-size = 96000
reasoning-preserve = true
